
#ifndef _GLOBAL_SETTING_H__
#define _GLOBAL_SETTING_H__

#define HEAP_EXECUTE_PROTECT
#define HEAP_LENGTH          1024*1000*3000  //  300 MB

#define PLATFORM_WINDOWS

HANDLE heap_handle=INVALID_HANDLE_VALUE;

#endif
